"""
Tournament Operator Gate API — Phase 29

HMAC-SHA256 signed eligibility endpoint for tournament operators.

Game servers can verify humanity credentials without blockchain knowledge.
Uses a single shared secret (OPERATOR_API_KEY env var) for v1.

Endpoints:
  GET  /health                     — API status + key-configured flag
  GET  /gate/{device_id}?api_key=  — Single-device eligibility check (signed)
  POST /gate/batch?api_key=        — Batch eligibility check (up to 50 devices)

Response signature:
  sig = HMAC-SHA256(f"{device_id}:{int(eligible)}:{timestamp}", api_key).hexdigest()
  Operators verify this to confirm the response was generated by the bridge.

Security:
  - api_key compared with hmac.compare_digest() (constant-time, no timing attacks)
  - 503 if OPERATOR_API_KEY not set (graceful degradation, not an auth bypass)
  - 403 if key is wrong
"""

import asyncio
import collections
import hashlib
import hmac
import json as _json
import logging
import os
import time

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

# Phase O0 Stream 4-prep Session 2 — agent token authentication.
from ..agent_auth import AgentIdentity, make_check_agent_token
from ..hmac_middleware import NonceDedupTracker
from ..oauth_issuer import OAuthIssuer

log = logging.getLogger(__name__)

from pathlib import Path as _PathLayout

# Package layout anchors (D-DECON-2: operator_api.py → operator_api/_app.py).
_OPERATOR_API_PKG_DIR = _PathLayout(__file__).resolve().parent
_VAPI_BRIDGE_DIR = _OPERATOR_API_PKG_DIR.parent
_BRIDGE_DIR = _VAPI_BRIDGE_DIR.parent
_REPO_ROOT = _BRIDGE_DIR.parent

_BATCH_CAP = 50


class _RateLimiter:
    """Sliding-window in-memory rate limiter (zero external dependencies).

    Tracks per-key request timestamps in a deque; evicts entries outside the
    60-second window on each check. Thread-safe in asyncio single-threaded context.
    """

    def __init__(self, requests_per_minute: int = 60):
        self._rpm = max(1, requests_per_minute)
        self._windows: collections.defaultdict = collections.defaultdict(collections.deque)

    def is_allowed(self, key: str) -> bool:
        """Return True if key is within rate limit; record this request.

        Uses time.monotonic() so wall-clock rollback (NTP, manual adjustment)
        cannot bypass the sliding window.
        """
        now = time.monotonic()
        cutoff = now - 60.0
        dq = self._windows[key]
        while dq and dq[0] < cutoff:
            dq.popleft()
        if len(dq) >= self._rpm:
            return False
        dq.append(now)
        return True




def create_operator_app(cfg, store, _agent=None, _calib_agent=None, chain=None, bus=None) -> FastAPI:
    """Create the Operator Gate API sub-app.

    Args:
        cfg:         Config instance (reads cfg.operator_api_key).
        store:       Store instance (reads PHG checkpoints and credential mints).
        _agent:      Optional pre-instantiated BridgeAgent (Phase 32).
        _calib_agent: Optional pre-instantiated CalibrationIntelligenceAgent (Phase 50).
        chain:       Optional ChainClient instance for on-chain calls (Phase 72).
    """

    app = FastAPI(title="VAPI Operator Gate API", version="1.0.0-phase50")

    # Phase 236-VAME — Application-Layer Message Envelope
    # Sidecar response-header authentication binding every JSON response to
    # the GIC chain head. Provides app-layer integrity above TLS — survives
    # decrypting proxies, rogue middle-boxes, browser-extension MITM, etc.
    # Headers: X-VAME-Commitment / -Chain-Head / -TS-NS / -Version / -Endpoint.
    # Skips: non-JSON responses, /health (cheap liveness), websocket upgrades.
    # Cached chain-head with short TTL keeps middleware off the SQLite hot path.
    from ..vame import stamp_response_headers as _vame_stamp_headers
    from starlette.middleware.base import BaseHTTPMiddleware
    from starlette.responses import Response as _StarletteResponse

    _vame_chain_head_cache = {"head": "", "expires_at": 0.0}
    _VAME_CHAIN_HEAD_TTL_S = 5.0

    def _vame_get_chain_head_hex() -> str:
        """Return the 16-byte chain-head prefix as a 32-char hex string.

        Cached for `_VAME_CHAIN_HEAD_TTL_S` seconds so we don't hammer SQLite
        on every request. The chain only advances at GIC-stamp cadence (≥5
        min), so a 5-second cache produces no observable staleness.
        """
        nonlocal _vame_chain_head_cache
        _now = time.time()
        if _now < _vame_chain_head_cache["expires_at"] and _vame_chain_head_cache["head"]:
            return _vame_chain_head_cache["head"]
        try:
            _grind_sid = getattr(cfg, "grind_session_id", "")
            prev = store.get_prev_grind_chain_hash(_grind_sid)
            head_hex = prev.hex() if prev else ""
        except Exception:
            head_hex = ""
        _vame_chain_head_cache["head"] = head_hex
        _vame_chain_head_cache["expires_at"] = _now + _VAME_CHAIN_HEAD_TTL_S
        return head_hex

    class _VAMEMiddleware(BaseHTTPMiddleware):
        """Stamp JSON responses with VAME v1 sidecar headers.

        Skips:
          - WebSocket upgrades and Server-Sent-Event streams
          - Non-JSON responses (HTML errors, redirects, etc.)
          - /health (cheap liveness probe; no chain binding to add)
          - Already-streaming responses with no readable body
        """

        async def dispatch(self, request, call_next):
            path = request.url.path or ""
            response = await call_next(request)

            # Skip rules — keep middleware lightweight
            if path.endswith("/health"):
                return response
            content_type = (response.headers.get("content-type") or "").lower()
            if "application/json" not in content_type:
                return response
            if response.status_code >= 500:
                # 5xx already an error; skip stamping to keep error pass-through clean
                return response

            # Read the response body (consumes the iterator; rebuild a fresh response)
            body_chunks: list[bytes] = []
            async for chunk in response.body_iterator:
                body_chunks.append(chunk)
            body_bytes = b"".join(body_chunks)

            # Compute and attach VAME headers
            try:
                head_hex = _vame_get_chain_head_hex()
                vame_headers = _vame_stamp_headers(head_hex, path, body_bytes)
            except Exception as e:
                log.debug("VAME stamp failed for %s: %s — passing through unstamped", path, e)
                vame_headers = {}

            # Rebuild response with original headers + VAME sidecar
            new_headers = dict(response.headers)
            new_headers.update(vame_headers)
            # content-length must reflect body_bytes if Starlette set one
            if "content-length" in new_headers:
                new_headers["content-length"] = str(len(body_bytes))
            return _StarletteResponse(
                content=body_bytes,
                status_code=response.status_code,
                headers=new_headers,
                media_type=response.media_type,
            )

    app.add_middleware(_VAMEMiddleware)

    # Phase 36: Per-instance rate limiter (not a global singleton)
    _rpm = int(getattr(cfg, "rate_limit_per_minute", 60))
    _limiter = _RateLimiter(requests_per_minute=_rpm)

    # Lazy-initialised BridgeAgent (None until first /agent request)
    _agent_instance = [_agent]
    # Lazy-initialised CalibrationIntelligenceAgent (Phase 50)
    _calib_agent_instance = [_calib_agent]

    def _get_agent():
        """Return the BridgeAgent instance, creating it on first call."""
        if _agent_instance[0] is None:
            try:
                from ..bridge_agent import BridgeAgent
                _agent_instance[0] = BridgeAgent(cfg, store)
            except ImportError:
                raise HTTPException(
                    503, "anthropic package not installed (pip install anthropic)"
                )
        return _agent_instance[0]

    def _get_calib_agent():
        """Return the CalibrationIntelligenceAgent instance (Phase 50)."""
        if _calib_agent_instance[0] is None:
            try:
                from ..calibration_intelligence_agent import CalibrationIntelligenceAgent
                _calib_agent_instance[0] = CalibrationIntelligenceAgent(cfg, store)
            except ImportError:
                raise HTTPException(
                    503, "anthropic package not installed (pip install anthropic)"
                )
        return _calib_agent_instance[0]

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _check_key(api_key: str) -> None:
        """Raise HTTP 503/403 if key is missing or wrong."""
        if not cfg.operator_api_key:
            raise HTTPException(503, "Operator API not configured (OPERATOR_API_KEY not set)")
        if not hmac.compare_digest(api_key, cfg.operator_api_key):
            raise HTTPException(403, "Invalid API key")

    def _check_rate(api_key: str) -> None:
        """Raise HTTP 429 if the api_key has exceeded the sliding-window rate limit (Phase 36)."""
        if not _limiter.is_allowed(api_key):
            raise HTTPException(
                status_code=429,
                detail="Rate limit exceeded",
                headers={"Retry-After": "60"},
            )

    def _check_read_key(x_api_key: str) -> None:
        """Phase 224 W1 fix: for read-only /agent/* status endpoints using x-api-key header.

        Validates the key when OPERATOR_API_KEY is configured (fail-open when not configured,
        so dev environments without a key still work). Always applies rate limiting.
        Returns 403 when key is wrong, never 503 (status endpoints are read-only).
        """
        if cfg.operator_api_key:
            if not hmac.compare_digest(x_api_key, cfg.operator_api_key):
                raise HTTPException(403, "Invalid x-api-key header")
        if not _limiter.is_allowed(x_api_key):
            raise HTTPException(
                status_code=429,
                detail="Rate limit exceeded",
                headers={"Retry-After": "60"},
            )

    # ------------------------------------------------------------------
    # Phase O0 Stream 4-prep Session 2 — agent token dependency setup.
    #
    # Builds the OAuthIssuer + NonceDedupTracker + _check_agent_token
    # FastAPI dependency at app construction time. Closure-captured by
    # the five Phase O0 read-only /agent/agent-* endpoints below; the
    # 154+ existing operator endpoints are unchanged and continue to
    # use _check_key / _check_read_key.
    #
    # If OAUTH_ISSUER_SECRET is unset OR no OAUTH_CLIENT_ID_<AGENT> /
    # OAUTH_CLIENT_SECRET_<AGENT> pair is configured, the issuer is
    # None and _check_agent_token raises 503 ("OAuth not configured")
    # for every agent endpoint request — mirrors the _check_key
    # not-configured pattern. Bridge dev environments without auth
    # setup remain runnable; only agent endpoints are gated.
    # ------------------------------------------------------------------
    _oauth_clients_dict: "dict[str, tuple[str, list[str]]]" = {}
    _oauth_issuer: "OAuthIssuer | None" = None
    # Defensive type checks: existing tests use MagicMock for cfg, where
    # attribute access auto-creates truthy MagicMock objects. Skip OAuth
    # setup unless the fields are real, non-empty literals of the
    # expected types. Real Config (frozen dataclass) trivially passes.
    _oauth_secret_raw = getattr(cfg, "oauth_issuer_secret", "")
    if isinstance(_oauth_secret_raw, str) and _oauth_secret_raw:
        _clients_raw = cfg.get_oauth_clients() if hasattr(cfg, "get_oauth_clients") else {}
        if isinstance(_clients_raw, dict) and _clients_raw:
            _ttl_raw = getattr(cfg, "oauth_token_ttl_seconds", 300)
            _ttl = int(_ttl_raw) if isinstance(_ttl_raw, int) else 300
            _iss_raw = getattr(cfg, "oauth_issuer_url", "vapi-bridge-oauth")
            _iss = _iss_raw if isinstance(_iss_raw, str) and _iss_raw else "vapi-bridge-oauth"
            _aud_raw = getattr(cfg, "oauth_audience", "vapi-bridge-agent-endpoints")
            _aud = _aud_raw if isinstance(_aud_raw, str) and _aud_raw else "vapi-bridge-agent-endpoints"
            _oauth_clients_dict = _clients_raw
            _oauth_issuer = OAuthIssuer(
                secret=_oauth_secret_raw, clients=_oauth_clients_dict,
                issuer=_iss, audience=_aud, ttl_seconds=_ttl,
            )
    _nonce_window_raw = getattr(cfg, "hmac_nonce_window_seconds", 600)
    _nonce_tracker = NonceDedupTracker(
        ttl_seconds=int(_nonce_window_raw) if isinstance(_nonce_window_raw, int) else 600,
    )
    _ts_tol_raw = getattr(cfg, "hmac_timestamp_tolerance_seconds", 300)
    _check_agent_token = make_check_agent_token(
        oauth_issuer=_oauth_issuer,
        oauth_clients=_oauth_clients_dict,
        nonce_tracker=_nonce_tracker,
        timestamp_tolerance_seconds=int(_ts_tol_raw) if isinstance(_ts_tol_raw, int) else 300,
    )

    def _sign(device_id: str, eligible: bool, ts: int) -> str:
        """Produce HMAC-SHA256 signature over device_id:eligible:timestamp."""
        msg = f"{device_id}:{int(eligible)}:{ts}".encode()
        return hmac.new(
            cfg.operator_api_key.encode(), msg, hashlib.sha256
        ).hexdigest()

    def _gate_response(device_id: str) -> dict:
        """Build a signed gate response dict for one device."""
        ts = int(time.time())
        checkpoint = store.get_last_phg_checkpoint(device_id)
        credential = store.get_credential_mint(device_id)
        score = checkpoint["last_committed_score"] if checkpoint else 0
        eligible = score > 0
        cred_id = credential["credential_id"] if credential else None
        sig = _sign(device_id, eligible, ts)
        return {
            "device_id":       device_id,
            "eligible":        eligible,
            "cumulative_score": score,
            "credential_id":   cred_id,
            "timestamp":       ts,
            "sig":             sig,
        }

    from .health_gate import register_health_gate_routes

    register_health_gate_routes(
        app,
        cfg=cfg,
        check_key=_check_key,
        check_rate=_check_rate,
        gate_response=_gate_response,
        batch_cap=_BATCH_CAP,
    )

    from .agent_consent import register_agent_consent_routes

    register_agent_consent_routes(
        app,
        cfg=cfg,
        store=store,
        chain=chain,
        check_key=_check_key,
        check_rate=_check_rate,
        check_read_key=_check_read_key,
    )

    from .agent_zkba_vpm import register_agent_zkba_vpm_routes

    register_agent_zkba_vpm_routes(
        app,
        cfg=cfg,
        store=store,
        check_read_key=_check_read_key,
        repo_root=_REPO_ROOT,
        bridge_dir=_BRIDGE_DIR,
    )

    from .agent_ioswarm import register_agent_ioswarm_routes

    register_agent_ioswarm_routes(
        app,
        cfg=cfg,
        store=store,
        chain=chain,
        check_key=_check_key,
        check_rate=_check_rate,
    )

    from .agent_calibration import register_agent_calibration_routes

    register_agent_calibration_routes(
        app,
        cfg=cfg,
        store=store,
        check_key=_check_key,
        check_rate=_check_rate,
        check_read_key=_check_read_key,
        repo_root=_REPO_ROOT,
    )

    from .agent_biometric import register_agent_biometric_routes

    register_agent_biometric_routes(
        app,
        cfg=cfg,
        store=store,
        chain=chain,
        check_key=_check_key,
        check_rate=_check_rate,
        check_read_key=_check_read_key,
    )

    from .agent_marketplace import register_agent_marketplace_routes

    register_agent_marketplace_routes(
        app,
        cfg=cfg,
        store=store,
        chain=chain,
        check_key=_check_key,
        check_rate=_check_rate,
        check_read_key=_check_read_key,
        repo_root=_REPO_ROOT,
        vapi_bridge_dir=_VAPI_BRIDGE_DIR,
    )

    from .agent_tournament import register_agent_tournament_routes

    register_agent_tournament_routes(
        app,
        cfg=cfg,
        store=store,
        check_key=_check_key,
        check_rate=_check_rate,
    )

    from .agent_operator_initiative import register_agent_operator_initiative_routes

    register_agent_operator_initiative_routes(
        app,
        cfg=cfg,
        store=store,
        check_key=_check_key,
        check_rate=_check_rate,
        check_read_key=_check_read_key,
        repo_root=_REPO_ROOT,
        vapi_bridge_dir=_VAPI_BRIDGE_DIR,
    )

    from .agent_grind import register_agent_grind_routes

    register_agent_grind_routes(
        app,
        cfg=cfg,
        store=store,
        chain=chain,
        check_key=_check_key,
        check_rate=_check_rate,
        check_read_key=_check_read_key,
        check_agent_token=_check_agent_token,
    )

    from .agent_supervisor import register_agent_supervisor_routes

    register_agent_supervisor_routes(
        app,
        cfg=cfg,
        store=store,
        chain=chain,
        check_key=_check_key,
        check_rate=_check_rate,
        check_read_key=_check_read_key,
        repo_root=_REPO_ROOT,
    )

    from .agent_misc import register_agent_misc_routes

    register_agent_misc_routes(
        app,
        cfg=cfg,
        store=store,
        chain=chain,
        bus=bus,
        get_agent=_get_agent,
        get_calib_agent=_get_calib_agent,
        check_key=_check_key,
        check_rate=_check_rate,
        check_read_key=_check_read_key,
        repo_root=_REPO_ROOT,
    )

    # ------------------------------------------------------------------
    # Phase 3 Path B — Gameplay Workflow Layer (player-facing session status)
    # ------------------------------------------------------------------
    # 60s TTL cache for on-chain eligibility VIEW calls so GET /player/session-status
    # can be polled at 5s without an RPC round-trip per request. Closure-captured; the
    # route mutates it in place (dict mutation needs no `nonlocal`).
    _eligibility_cache: dict = {}

    def _bridge_local_eligible(device_id: str) -> bool:
        """Bridge-local proxy for VAPIProtocolLens.isFullyEligible (see
        KNOWN_EXTERNAL_BEHAVIORS.md): enrolled AND credential minted AND not suspended.
        Meaningful when the on-chain lens view is unavailable (bridge offline, RPC down,
        or device not yet on-chain-enrolled). Fail-closed on any error."""
        try:
            enrolled  = store.get_enrollment(device_id) is not None
            minted    = store.get_credential_mint(device_id) is not None
            suspended = bool(store.is_credential_suspended(device_id))
            return enrolled and minted and not suspended
        except Exception:
            return False

    # ------------------------------------------------------------------
    # Routes (domain register-functions; health/gate in health_gate.py)
    # ------------------------------------------------------------------

    # Trio-Retina advisory perception — GET /bridge/retina-status
    # ------------------------------------------------------------------
    @app.get("/bridge/retina-policy-status")
    async def get_retina_policy_status(
        x_api_key: str = Header(default=""),
    ):
        """Retina DePIN policy governor — qualifiers and effective flags."""
        _check_read_key(x_api_key)
        import time as _t_rpol
        from ..retina_depin_policy import (
            get_runtime_policy_state,
            qualifiers_summary,
        )

        _state = getattr(app, "_retina_policy_state", None) or get_runtime_policy_state()
        _snap = _state.to_dict() if _state else {}
        _log = await asyncio.to_thread(store.get_retina_policy_status, 5)
        return {
            "retina_policy_auto_arm": bool(
                getattr(cfg, "retina_policy_auto_arm", True)
            ),
            "retina_perception_enabled": bool(
                getattr(cfg, "retina_perception_enabled", False)
            ),
            "retina_external_ingest_enabled": bool(
                getattr(cfg, "retina_external_ingest_enabled", False)
            ),
            "armed": bool(_snap.get("armed", False)),
            "arm_source": _snap.get("arm_source", "unarmed"),
            "qualifiers": _snap.get("qualifiers", {}),
            "qualifiers_summary": qualifiers_summary(_state),
            "effective_perception": bool(_snap.get("effective_perception", False)),
            "effective_fsca": bool(_snap.get("effective_fsca", False)),
            "effective_adjudicator": bool(_snap.get("effective_adjudicator", False)),
            "policy_log": _log,
            "timestamp": _t_rpol.time(),
        }

    @app.get("/bridge/retina-w3bstream-status")
    async def get_retina_w3bstream_status(
        x_api_key: str = Header(default=""),
    ):
        """W3bstream mechanical validation status for Retina sidecar pointers."""
        _check_read_key(x_api_key)
        import time as _t_w3s

        _log = await asyncio.to_thread(store.get_retina_w3bstream_status, 5)
        return {
            "retina_w3bstream_validation_enabled": bool(
                getattr(cfg, "retina_w3bstream_validation_enabled", False)
            ),
            "retina_w3bstream_enforce_on_ingest": bool(
                getattr(cfg, "retina_w3bstream_enforce_on_ingest", False)
            ),
            "latest_exit_code": int(_log.get("latest_exit_code") or 0),
            "validation_log": _log,
            "timestamp": _t_w3s.time(),
        }

    @app.get("/bridge/retina-da-status")
    async def get_retina_da_status(
        x_api_key: str = Header(default=""),
    ):
        """DePIN DA bulk upload status for retina_event_log sidecar blobs."""
        _check_read_key(x_api_key)
        import time as _t_da

        _log = await asyncio.to_thread(store.get_retina_da_upload_status, 5)
        return {
            "retina_da_upload_enabled": bool(
                getattr(cfg, "retina_da_upload_enabled", False)
            ),
            "latest_uploaded": bool(_log.get("latest_uploaded")),
            "latest_payload_bytes": int(_log.get("latest_payload_bytes") or 0),
            "upload_log": _log,
            "timestamp": _t_da.time(),
        }

    @app.get("/bridge/retina-pda-status")
    async def get_retina_pda_status(
        x_api_key: str = Header(default=""),
    ):
        """PHYSICAL_DATA_ATTESTATION status for Retina perception sidecar pointers."""
        _check_read_key(x_api_key)
        import time as _t_pda

        _status = await asyncio.to_thread(
            store.get_physical_data_attestation_status,
        )
        _history = await asyncio.to_thread(
            lambda: store.get_physical_data_attestation_history(
                attestation_type="RETINA_PERCEPTION_OBSERVATION",
                limit=5,
            ),
        )
        return {
            "retina_pda_attestation_enabled": bool(
                getattr(cfg, "retina_pda_attestation_enabled", False)
            ),
            "retina_pda_attestation_agent_id": str(
                getattr(cfg, "retina_pda_attestation_agent_id", "bridge_agent")
            ),
            "pda_status": _status,
            "retina_attestation_history": _history,
            "timestamp": _t_pda.time(),
        }

    @app.get("/bridge/retina-status")
    async def get_retina_status(
        device_id: str = Query(default=""),
        limit: int = Query(default=20, ge=1, le=100),
        x_api_key: str = Header(default=""),
    ):
        """Retina perception log status (advisory sidecar; default OFF)."""
        _check_read_key(x_api_key)
        import time as _t_ret
        try:
            _status = await asyncio.to_thread(
                store.get_retina_event_status,
                device_id or None,
                limit,
            )
            return {
                **_status,
                "retina_perception_enabled": bool(
                    getattr(cfg, "retina_perception_enabled", False)
                ),
                "retina_perception_effective": __import__(
                    "bridge.vapi_bridge.retina_depin_policy",
                    fromlist=["is_effective_perception"],
                ).is_effective_perception(cfg),
                "retina_perception_window": int(
                    getattr(cfg, "retina_perception_window", 120)
                ),
                "timestamp": _t_ret.time(),
            }
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc)) from exc

    @app.get("/bridge/retina-alerts")
    async def get_retina_alerts(
        since: float = Query(default=0.0),
        limit: int = Query(default=50, ge=1, le=200),
        x_api_key: str = Header(default=""),
    ):
        """Anomaly rows from retina_event_log since ``since`` unix timestamp."""
        _check_read_key(x_api_key)
        import time as _t_ret_a
        try:
            _alerts = await asyncio.to_thread(
                store.get_retina_alerts_since, since, limit
            )
            return {
                "alerts": _alerts,
                "count": len(_alerts),
                "retina_perception_enabled": bool(
                    getattr(cfg, "retina_perception_enabled", False)
                ),
                "timestamp": _t_ret_a.time(),
            }
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc)) from exc

    @app.post("/operator/retina-event")
    async def ingest_retina_event(
        request: Request,
        api_key: str = Query(default=""),
    ):
        """Ingest external trio-retina WebhookSink payloads (Phase C)."""
        _check_key(api_key)
        if not bool(getattr(cfg, "retina_external_ingest_enabled", False)):
            raise HTTPException(
                status_code=403,
                detail="RETINA_EXTERNAL_INGEST_ENABLED=false — webhook ingest disabled",
            )
        import time as _t_ret_ev
        try:
            body = await request.json()
        except Exception as exc:
            raise HTTPException(status_code=422, detail="invalid JSON body") from exc
        _device_id = str(body.get("device_id") or body.get("source_id") or "external")
        _events = body.get("events") or []
        if not isinstance(_events, list):
            raise HTTPException(status_code=422, detail="events must be a list")
        _ws = body.get("world_state") or body.get("world_state_json") or ""
        if isinstance(_ws, dict):
            _ws = _json.dumps(_ws, separators=(",", ":"))
        _record_hash = str(body.get("record_hash") or body.get("record_hash_hex") or "")
        _anomaly_count = int(body.get("anomaly_count") or len(_events))
        _commitment = str(body.get("state_commitment") or body.get("state_commitment_hex") or "")
        if not _commitment and _events:
            from ..retina_state_commitment import compute_retina_state_commitment
            _commitment = compute_retina_state_commitment(
                _device_id, int(body.get("ts_ns") or _t_ret_ev.time_ns()), _events
            )
        _row_id = await asyncio.to_thread(
            store.insert_retina_event_batch,
            device_id=_device_id,
            events_json=_json.dumps(_events),
            world_state_json=str(_ws),
            record_hash_hex=_record_hash,
            anomaly_count=_anomaly_count,
            state_commitment_hex=_commitment,
            ts_ns=int(body.get("ts_ns") or _t_ret_ev.time_ns()),
            source="webhook",
        )
        return {
            "accepted": True,
            "row_id": _row_id,
            "device_id": _device_id,
            "event_count": len(_events),
            "timestamp": _t_ret_ev.time(),
        }

    @app.get("/bridge/retina-stream")
    async def retina_alert_stream(
        x_api_key: str = Header(default=""),
    ):
        """SSE stream of retina anomaly alerts (polls store every 2s)."""
        _check_read_key(x_api_key)

        async def _gen():
            import time as _t_sse
            _since = _t_sse.time() - 5.0
            while True:
                try:
                    _alerts = await asyncio.to_thread(
                        store.get_retina_alerts_since, _since, 20
                    )
                    for _a in reversed(_alerts):
                        _created = float(_a.get("created_at") or 0.0)
                        if _created > _since:
                            yield f"data: {_json.dumps(_a)}\n\n"
                            _since = max(_since, _created)
                except Exception:
                    pass
                await asyncio.sleep(2.0)

        return StreamingResponse(_gen(), media_type="text/event-stream")

    @app.get("/agent/retina-evidence-slice")
    async def get_retina_evidence_slice(
        device_id: str = Query(..., min_length=1),
        record_hashes: str = Query(default=""),
        limit: int = Query(default=10, ge=1, le=50),
        x_api_key: str = Header(default=""),
    ):
        """Read-only Retina bindings for SessionAdjudicator cross-oracle evidence."""
        _check_read_key(x_api_key)
        import time as _t_ret_ev
        from ..retina_perception import build_retina_evidence_slice

        _hash_list: list[str] = []
        if record_hashes.strip():
            _hash_list = [h.strip() for h in record_hashes.split(",") if h.strip()]
        _enabled = __import__(
            "bridge.vapi_bridge.retina_depin_policy",
            fromlist=["is_effective_adjudicator"],
        ).is_effective_adjudicator(cfg)
        try:
            _slice = await asyncio.to_thread(
                build_retina_evidence_slice,
                store,
                device_id,
                record_hashes=_hash_list or None,
                limit=min(limit, 50),
                enabled=_enabled,
            )
            return {
                **_slice,
                "device_id": device_id,
                "timestamp": _t_ret_ev.time(),
            }
        except Exception as exc:
            log.warning("retina-evidence-slice fail-open: %s", exc)
            return {
                "schema": "vapi-retina-event-v1",
                "enabled": _enabled,
                "bindings": [],
                "aggregate": {
                    "total_trajectory_anomalies": 0,
                    "latest_state_commitment": "",
                    "rows_matched": 0,
                },
                "device_id": device_id,
                "timestamp": _t_ret_ev.time(),
            }


    # Phase 3 Path B — Gameplay Workflow Layer: GET /player/session-status
    # ------------------------------------------------------------------
    # Single-glance "am I verified?" for the casual player. Read-only COMPOSITION over
    # existing surfaces (capture health + latest PoAC record + on-chain isFullyEligible +
    # bridge-local proxy + dual-primitive + VHP + GIC chain + enforcement state). Adds NO
    # new capture/adjudication authority. Every chain call is a pure VIEW — kill-switch safe.
    @app.get("/player/session-status")
    async def player_session_status(
        device_id: str = Query(default="", description="Device id; defaults to the most recent active device"),
        x_api_key: str = Header(default=""),
    ):
        _check_read_key(x_api_key)
        import time as _t_pss
        _now = _t_pss.time()
        _enf = bool(getattr(cfg, "ipact_renewal_enforcement_enabled", False))
        _hs  = bool(getattr(cfg, "ipact_host_signer_enabled", False))
        from ..cco_poep_bridge import (
            assemble_poep_presence_status,
            build_poep_telemetry_from_probe,
            resolve_capability_report_for_session,
        )
        from ..cco_identity_grid import assemble_identity_grid
        from ..cco_composability import (
            apply_composability_to_grid,
            assemble_composability_status,
            resolve_poep_commitment,
        )
        from ..cco_controller_class_research import (
            assemble_controller_class_research,
            enrich_phase_g_progress,
            parse_phase_g_deferred_tiers,
            parse_phase_g_validated_tiers,
            resolve_controller_class_tier,
        )

        _poep_enabled = bool(getattr(cfg, "poep_enabled", False))
        _poep_corpus = getattr(cfg, "poep_corpus_dir", "poep_l9") or "poep_l9"
        _comp_enabled = bool(getattr(cfg, "cco_composability_enabled", False))
        _lens_subcheck = bool(getattr(cfg, "cco_composability_lens_subcheck", False))
        _registry_deployed = bool(getattr(cfg, "poep_registry_address", "") or "")
        _research_enabled = bool(getattr(cfg, "cco_research_surface_enabled", False))
        _deferred_tiers = parse_phase_g_deferred_tiers(
            getattr(cfg, "cco_phase_g_deferred_tiers", "") or "",
        )
        _validated_tiers = parse_phase_g_validated_tiers(
            getattr(cfg, "cco_phase_g_validated_tiers", "") or "",
        )
        _phase_g_progress = None
        if _research_enabled:
            _phase_g_progress = await asyncio.to_thread(
                store.get_cco_phase_g_corpus_progress,
            )
            if _phase_g_progress is not None:
                _phase_g_progress = enrich_phase_g_progress(
                    _phase_g_progress,
                    deferred_tiers=_deferred_tiers,
                    validated_tiers=_validated_tiers,
                )

        def _tier_probe_count_for(profile_id: str | None) -> int | None:
            if _phase_g_progress is None:
                return None
            tier = resolve_controller_class_tier(profile_id)
            return _phase_g_progress["by_tier"][tier]["probe_count"]

        def _controller_class_research(
            *,
            profile_id: str | None = None,
            characterization_status: str | None = None,
        ) -> dict:
            block = assemble_controller_class_research(
                enabled=_research_enabled,
                profile_id=profile_id,
                characterization_status=characterization_status,
                tier_probe_count=_tier_probe_count_for(profile_id),
                validated_tiers=_validated_tiers,
                deferred_tiers=_deferred_tiers,
            )
            if _research_enabled and _phase_g_progress is not None:
                block["phase_g_by_tier"] = _phase_g_progress["by_tier"]
                if _phase_g_progress.get("deferred_tiers"):
                    block["deferred_tiers"] = _phase_g_progress["deferred_tiers"]
                if _phase_g_progress.get("validated_tiers"):
                    block["validated_tiers"] = _phase_g_progress["validated_tiers"]
            return block

        _identity_grid_empty = apply_composability_to_grid(
            assemble_identity_grid(),
            assemble_composability_status(
                enabled=_comp_enabled,
                registry_deployed=_registry_deployed,
            ),
        )
        _identity_grid_empty["controller_class_research"] = _controller_class_research()
        _presence = {
            "poep": assemble_poep_presence_status(
                poep_enabled=_poep_enabled,
                capability_report=None,
                corpus_dir=_poep_corpus,
            ),
            "bcc":  {"enabled": False, "status": "dormant"},
        }
        _cco_empty = {
            "t0_engine": None,
            "presence_ceiling_candidate": None,
            "identity_class": None,
            "profile_id": None,
            "challenge_type_candidate": None,
            "policy_ref": None,
            "reflex_verdict": None,
            "l6b_enabled": bool(getattr(cfg, "l6b_enabled", False)),
            "l6b_applicable": False,
            "l6b_skip": None,
            "calibration": {
                "probe_count": 0,
                "target_n": 50,
                "gate_reached": False,
                "reflex_verdict_distribution": {},
            },
        }

        # --- device resolution: explicit ?device_id=, else most-recent record ---
        dev = device_id
        if not dev:
            _recent = await asyncio.to_thread(store.get_recent_records, 1, None)
            dev = _recent[0]["device_id"] if _recent else ""
        if not dev:
            return {
                "controller_connected": False, "session_active": False, "device_id": "",
                "humanity_prob": None, "pitl_layers": {},
                "is_fully_eligible": {"onchain": None, "bridge_local": False, "source": "no_device"},
                "dual_eligible": {"available": False, "source": "no_device"},
                "vhp_status": None,
                "gic_chain": {"length": 0, "integrity": "empty", "last_anchor": None},
                "records_count": {"device": 0,
                                  "total": await asyncio.to_thread(store.count_records, None)},
                "enforcement_active": _enf, "host_signer_active": _hs,
                "last_adjudication": None, "presence": _presence,
                "cco": _cco_empty,
                "signing_path": None,
                "proof_tier": None,
                "controller_model": None,
                "path_a_eligible": False,
                "identity_grid": _identity_grid_empty,
                "timestamp": _now,
            }

        # --- capture health → connection + activity ---
        _cap = await asyncio.to_thread(store.get_capture_health_status, 5)
        _cap_state = _cap.get("capture_state", "DISCONNECTED")
        controller_connected = _cap_state in ("NOMINAL", "DEGRADED")

        # --- latest record → humanity + PITL layer snapshot ---
        _recent_dev = await asyncio.to_thread(store.get_recent_records, 1, dev)
        _rec = _recent_dev[0] if _recent_dev else {}
        _hp = _rec.get("pitl_humanity_prob")
        humanity_prob = float(_hp) if _hp is not None else None
        _rec_age = (_now - float(_rec.get("created_at", 0.0))) if _rec else 1e9
        session_active = controller_connected and _rec_age <= 120.0
        _infer = _rec.get("inference")
        # Honest layer snapshot: only what the record actually carries. inference==0x20 (32) is
        # the NOMINAL L2/L3 verdict; L4 distance is raw (lower is better, threshold 7.009). L0/L1/L5
        # are not stored per-record, so they are reported as null rather than fabricated as "pass".
        pitl_layers = {
            "inference_code": int(_infer) if _infer is not None else None,
            "nominal": (int(_infer) == 32) if _infer is not None else None,
            "l4_distance": (float(_rec["pitl_l4_distance"]) if _rec.get("pitl_l4_distance") is not None else None),
            "humanity_prob": humanity_prob,
        }

        # --- on-chain isFullyEligible (cached 60s) + bridge-local proxy ---
        _cached = _eligibility_cache.get(dev)
        if _cached and (_now - _cached["ts"] < 60.0):
            _elig = _cached["value"]
        else:
            import hashlib as _hl_pss
            _dev_hash = _hl_pss.sha256(dev.encode()).hexdigest()
            _onchain, _source = None, "unavailable"
            if chain is not None:
                try:
                    # Bound the on-chain read: on a slow/rate-limited IoTeX testnet
                    # RPC this await can hang for the full RPC latency, blocking the
                    # whole endpoint (gamer dashboard box shows all-dashes instead
                    # of local data). 2s cap → fail fast to "unavailable" (NO CHAIN)
                    # while humanity / enforcement / vhp still populate from local.
                    _onchain = bool(await asyncio.wait_for(
                        chain.is_fully_eligible(_dev_hash), timeout=2.0))
                    _source = "onchain"
                except Exception as _exc_elig:
                    log.debug("player_session_status: isFullyEligible unavailable: %s", _exc_elig)
            _elig = {"onchain": _onchain, "source": _source}
            _eligibility_cache[dev] = {"ts": _now, "value": _elig}
        is_fully_eligible = {
            "onchain":      _elig["onchain"],
            "bridge_local": _bridge_local_eligible(dev),
            "source":       _elig["source"],
        }

        # --- dual-primitive (secondary; requires a PoAd, so often "unavailable" in casual play) ---
        dual_eligible = {"available": False, "source": "unavailable"}

        # --- VHP status ---
        vhp_status = None
        _vhp = await asyncio.to_thread(store.get_vhp_status, dev)
        if _vhp:
            _exp = _vhp.get("expires_at")
            _renew = await asyncio.to_thread(store.get_vhp_renewal_log, dev, 1)
            vhp_status = {
                "valid": bool(_exp and float(_exp) > _now),
                "expires_in_days": (round((float(_exp) - _now) / 86400.0, 1) if _exp else None),
                "last_renewed": (_renew[0].get("new_expires_at") if _renew else None),
            }

        # --- GIC chain (DISTINCT from records_count) ---
        _gic = await asyncio.to_thread(store.get_grind_chain_status, getattr(cfg, "grind_session_id", ""), cfg)
        gic_chain = {
            "length":      _gic.get("chain_length", 0),
            "integrity":   "intact" if _gic.get("chain_intact", True) else "broken",
            "last_anchor": (_gic.get("latest_gic_hash") or None),
        }

        # --- last adjudication ---
        last_adjudication = None
        try:
            _rulings = await asyncio.to_thread(store.get_agent_rulings, dev, 1)
            if _rulings:
                _r0 = _rulings[0]
                last_adjudication = {
                    "verdict": _r0.get("verdict"),
                    "confidence": _r0.get("confidence"),
                    "ts": _r0.get("created_at"),
                }
        except Exception as _exc_rul:
            log.debug("player_session_status: rulings unavailable: %s", _exc_rul)

        # --- Path A Arc 1 Commit 4 additions ---
        # signing_path: 1->"A", 2->"B", 0->None (unregistered in MFG registry)
        # proof_tier:   1->"FULL", 2->"STANDARD", 3->"BASIC", 0->None
        # controller_model: reverse-lookup via controller_models.name_for_hash
        # path_a_eligible: composite via lens v2 (isFullyEligible AND isPathA AND active)
        signing_path = None
        proof_tier   = None
        controller_model = None
        path_a_eligible  = False

        # These are advisory MFG-registry / Path A chain reads. On a slow/rate-
        # limited IoTeX RPC each can block for the full RPC latency; several
        # sequential reads hang this 5s-polled endpoint (the dashboard box shows
        # all-dashes). Bound the WHOLE section to 2s — on timeout the fields stay
        # at their honest defaults (None / False) while the rest of the payload
        # (humanity / capture / GIC / VHP / enforcement) returns immediately.
        async def _read_path_a_fields():
            nonlocal signing_path, proof_tier, controller_model, path_a_eligible
            try:
                _sp = await asyncio.to_thread(chain.get_device_signing_path, dev) if chain else 0
                signing_path = {1: "A", 2: "B"}.get(int(_sp))
                _pt = await asyncio.to_thread(chain.get_proof_tier, dev) if chain else 0
                proof_tier = {1: "FULL", 2: "STANDARD", 3: "BASIC"}.get(int(_pt))
                if chain:
                    _cm_bytes = await asyncio.to_thread(chain.get_device_controller_model, dev)
                    if _cm_bytes is not None:
                        from ..controller_models import name_for_hash as _name_for_hash
                        controller_model = _name_for_hash(_cm_bytes)
            except Exception as _exc_mfg:
                log.debug("player_session_status: MFG registry read unavailable (honest dormant): %s", _exc_mfg)
            try:
                if chain is not None:
                    import hashlib as _hl_pa
                    _dev_hash = _hl_pa.sha256(dev.encode()).hexdigest()
                    path_a_eligible = bool(await asyncio.wait_for(
                        chain.is_fully_eligible_path_a(_dev_hash), timeout=2.0))
            except Exception as _exc_pa:
                log.debug("player_session_status: isFullyEligible_PathA unavailable (honest false): %s", _exc_pa)
        try:
            await asyncio.wait_for(_read_path_a_fields(), timeout=2.0)
        except Exception as _exc_pa_to:
            log.debug("player_session_status: Path A chain reads timed out (honest defaults): %s", _exc_pa_to)

        # --- CCO Phase B.2 — read-only T0 / L6B telemetry surface ---
        from ..cco_l6b_wiring import assemble_cco_session_status

        _l6b_prog = await asyncio.to_thread(store.get_l6b_calibration_progress, dev)
        _global_n = int(_l6b_prog.get("probe_count", 0))
        _l6b_gate = bool(_l6b_prog.get("gate_reached", False))
        _latest_probe = _l6b_prog.get("latest_probe")
        _transport = getattr(app, "_transport", None)
        _cco_report = None
        try:
            _cco_report = await asyncio.to_thread(
                resolve_capability_report_for_session,
                cfg=cfg,
                transport=_transport,
                device_id_hex=dev,
                signing_path=signing_path,
            )
        except Exception as _exc_cco:
            log.debug("player_session_status: CapabilityOracle resolve failed: %s", _exc_cco)
        _cco = assemble_cco_session_status(
            capability_report=_cco_report,
            l6b_calibration_progress=_l6b_prog,
            l6b_enabled=bool(getattr(cfg, "l6b_enabled", False)),
            controller_connected=controller_connected,
        )
        _poep_ct = (
            getattr(_cco_report, "challenge_type_candidate", None)
            if _cco_report is not None
            else None
        )
        _poep_telemetry = build_poep_telemetry_from_probe(
            _poep_ct,
            _l6b_prog.get("latest_probe"),
        )
        _presence["poep"] = assemble_poep_presence_status(
            poep_enabled=_poep_enabled,
            capability_report=_cco_report,
            device_id=dev or None,
            l6b_probe_count=_global_n,
            l6b_gate_reached=_l6b_gate,
            corpus_dir=_poep_corpus,
            device_auth=_poep_telemetry.get("device_auth"),
            reaction_features=_poep_telemetry.get("reaction_features"),
            latest_probe=_latest_probe,
            device_auth_note=_poep_telemetry.get("device_auth_note"),
        )
        _identity_grid = assemble_identity_grid(
            capability_report=_cco_report,
            signing_path=signing_path,
            path_a_eligible=path_a_eligible,
            device_id=dev or None,
        )
        _poep_commitment = None
        _poep_recorded = None
        _poep_scan_outcome = None
        _poep_scan_error = None
        if chain is not None and _registry_deployed:
            try:
                _reader, _poep_scan_outcome, _poep_scan_error = await asyncio.to_thread(
                    chain.lookup_poep_device_for_composability, dev
                )
                if _reader is not None:
                    _poep_commitment, _poep_recorded = resolve_poep_commitment(_reader, dev)
            except Exception as _exc_poep_c:
                log.debug("player_session_status: PoEP composability read failed: %s", _exc_poep_c)
                _poep_scan_outcome = "SCAN_FAILED"
                _poep_scan_error = str(_exc_poep_c)
        _composability = assemble_composability_status(
            enabled=_comp_enabled,
            registry_deployed=_registry_deployed,
            device_id=dev or None,
            identity_class=_identity_grid.get("identity_class"),
            presence_tier=_identity_grid.get("presence_ceiling_candidate"),
            poep_commitment=_poep_commitment,
            poep_commitment_recorded=_poep_recorded,
            poep_scan_outcome=_poep_scan_outcome,
            poep_scan_error=_poep_scan_error,
            is_fully_eligible_onchain=_elig.get("onchain") if _lens_subcheck else None,
            lens_subcheck_enabled=_lens_subcheck,
            ts_ns=int(_now * 1e9),
        )
        _identity_grid = apply_composability_to_grid(_identity_grid, _composability)
        _identity_grid["controller_class_research"] = _controller_class_research(
            profile_id=_cco_report.profile_id if _cco_report else None,
            characterization_status=_cco_report.characterization_status if _cco_report else None,
        )

        return {
            "controller_connected": controller_connected,
            "session_active": session_active,
            "device_id": dev,
            "capture_state": _cap_state,
            "host_state": _cap.get("host_state", "UNKNOWN"),
            "poll_rate_hz": _cap.get("poll_rate_hz", 0.0),
            "humanity_prob": humanity_prob,
            "pitl_layers": pitl_layers,
            "is_fully_eligible": is_fully_eligible,
            "dual_eligible": dual_eligible,
            "vhp_status": vhp_status,
            "gic_chain": gic_chain,
            "records_count": {
                "device": await asyncio.to_thread(store.count_records, dev),
                "total":  await asyncio.to_thread(store.count_records, None),
            },
            "enforcement_active": _enf,
            "host_signer_active": _hs,
            "last_adjudication": last_adjudication,
            "presence": _presence,
            # Path A Arc 1 Commit 4 — manufacturer attestation surface (honest
            # dormant defaults when MFG registry unread or device not registered)
            "signing_path":     signing_path,
            "proof_tier":       proof_tier,
            "controller_model": controller_model,
            "path_a_eligible":  path_a_eligible,
            "identity_grid": _identity_grid,
            "cco": _cco,
            "retina_policy_armed": bool(
                getattr(
                    getattr(app, "_retina_policy_state", None),
                    "armed",
                    False,
                )
            ),
            "retina_policy_arm_source": (
                getattr(
                    getattr(app, "_retina_policy_state", None),
                    "arm_source",
                    "unarmed",
                )
            ),
            "retina_qualifiers_summary": __import__(
                "bridge.vapi_bridge.retina_depin_policy",
                fromlist=["get_runtime_policy_state", "qualifiers_summary"],
            ).qualifiers_summary(
                getattr(app, "_retina_policy_state", None)
                or __import__(
                    "bridge.vapi_bridge.retina_depin_policy",
                    fromlist=["get_runtime_policy_state"],
                ).get_runtime_policy_state()
            ),
            "timestamp": _now,
        }


    # Phase B item ② P4b — GET /operator/poep-registry/{device_id}
    # ------------------------------------------------------------------
    # Read-only: returns a device's registered composite pubkey (integrity-verified via the
    # two-RPC pattern in chain.get_registered_composite_pubkey). Fail-open: when the registry
    # is undeployed (v1) registered=False/registry_deployed=False. The bridge never writes;
    # gamers register via their own wallet (W1).
    @app.get("/operator/poep-registry/{device_id}")
    def get_poep_registry(
        device_id: str,
        x_api_key: str = Header(default=""),
    ):
        """Composite-pubkey registration lookup for a device (Phase B ②).

        Returns: device_id, registry_deployed (bool), registered (bool),
        composite_pubkey_hex (str|None — the integrity-verified ① encode_pubkey blob).
        """
        _check_read_key(x_api_key)
        deployed = bool(getattr(cfg, "poep_registry_address", "") or "")
        blob = None
        if chain is not None:
            try:
                blob = chain.get_registered_composite_pubkey(device_id)
            except Exception:
                blob = None
        return {
            "device_id": device_id,
            "registry_deployed": deployed,
            "registered": blob is not None,
            "composite_pubkey_hex": blob.hex() if blob else None,
        }



    return app
