#!/usr/bin/env python3
"""
buzz_agent_factory.py — Agentic agent and channel creation for the QorTroller Buzz plane.

This script lets an authorized parent agent (operator or delegated agent) create:
  1. New Buzz channels (`create-channel`).
  2. New child agents (`create-agent`) — fresh nsec, kind 0 profile, and an
     optional birth announcement on an audit channel.

The parent signs everything. The child nsec is written to a gitignored `.env`
file so the new agent can be started immediately.

Authority model:
  - Parent provides `BUZZ_PRIVATE_KEY` (its own key).
  - Optional `BUZZ_LOBBY_CHANNEL_ID` / `BUZZ_AUDIT_CHANNEL_ID` for birth posts.
  - No limit on children unless the caller imposes one (operator policy lives
    outside this tool, e.g. `ACP_OPERATOR_PUBKEYS` in the relay bot).

Usage:
  $env:BUZZ_PRIVATE_KEY = "nsec1..."
  $env:BUZZ_RELAY_URL = "https://qortroller.communities.buzz.xyz"
  python scripts/buzz_agent_factory.py create-channel --name "test" --description "test"
  python scripts/buzz_agent_factory.py create-agent --name "AlphaBot" --role "watcher"
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / "agents"
AGENTS_DIR.mkdir(parents=True, exist_ok=True)


def _raw_to_http(url: str) -> str:
    if url.startswith("ws://"):
        return "http://" + url[len("ws://"):]
    if url.startswith("wss://"):
        return "https://" + url[len("wss://"):]
    return url


def _raw_to_ws(url: str) -> str:
    if url.startswith("http://"):
        return "ws://" + url[len("http://"):]
    if url.startswith("https://"):
        return "wss://" + url[len("https://"):]
    return url


def _cli_path() -> str:
    env = os.environ.get("BUZZ_CLI_PATH", "")
    if env and os.path.isfile(env):
        return env
    default = str(REPO_ROOT / "buzz" / "target" / "debug" / "buzz.exe")
    if os.path.isfile(default):
        return default
    return env or default


def _helper_path() -> str:
    env = os.environ.get("BUZZ_HELPER_PATH", "")
    if env and os.path.isfile(env):
        return env
    default = str(REPO_ROOT / "buzz" / "target" / "debug" / "qortroller-buzz.exe")
    if os.path.isfile(default):
        return default
    return env or default


def _buzz_cli(args: list[str], extra_env: Optional[dict] = None, timeout: float = 30) -> tuple[int, str, str]:
    env = os.environ.copy()
    env["BUZZ_RELAY_URL"] = _raw_to_http(env.get("BUZZ_RELAY_URL", "http://localhost:3000"))
    if extra_env:
        env.update(extra_env)
    try:
        result = subprocess.run(
            [_cli_path()] + args,
            capture_output=True,
            text=True,
            timeout=timeout,
            env=env,
            shell=False,
            cwd=REPO_ROOT,
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()
    except Exception as e:
        return 1, "", str(e)


def _qortroller_buzz(args: list[str], stdin: str = "", extra_env: Optional[dict] = None, timeout: float = 30) -> tuple[int, str, str]:
    env = os.environ.copy()
    env["BUZZ_RELAY_URL"] = _raw_to_ws(env.get("BUZZ_RELAY_URL", "ws://localhost:3000"))
    env.pop("BUZZ_AUTH_TAG", None)
    if extra_env:
        env.update(extra_env)
    try:
        result = subprocess.run(
            [_helper_path()] + args,
            input=stdin,
            capture_output=True,
            text=True,
            timeout=timeout,
            env=env,
            shell=False,
            cwd=REPO_ROOT,
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()
    except Exception as e:
        return 1, "", str(e)


def _my_npub(private_key: str) -> str:
    try:
        from nostr_sdk import Keys
        return Keys.parse(private_key).public_key().to_bech32()
    except Exception as e:
        print(f"[!] could not derive npub: {e}", file=sys.stderr)
        return ""


def _generate_key() -> tuple[str, str]:
    """Generate (nsec, npub) for a new child agent."""
    try:
        from nostr_sdk import Keys
        keys = Keys.generate()
        nsec = keys.secret_key().to_bech32()
        npub = keys.public_key().to_bech32()
        return nsec, npub
    except Exception as e:
        print(f"[!] key generation failed: {e}", file=sys.stderr)
        sys.exit(1)


def _write_child_env(name: str, nsec: str, npub: str, relay_url: str, role: str, parent_npub: str) -> Path:
    env_path = AGENTS_DIR / f"{name}.env"
    env_text = f"""# Child agent env for {name} — generated by buzz_agent_factory.py
# DO NOT COMMIT. Keep this secret.
BUZZ_PRIVATE_KEY={nsec}
BUZZ_RELAY_URL={relay_url}
BUZZ_PERSONAL_AGENT_NAME={name}
BUZZ_PERSONAL_AGENT_ABOUT=Child QorTroller agent ({role}) minted by {parent_npub}.
BUZZ_PERSONAL_AGENT_ENABLED=0
# Set BUZZ_LOBBY_CHANNEL_ID and BUZZ_PERSONAL_AGENT_DM_IDS, then enable.
"""
    env_path.write_text(env_text, encoding="utf-8")
    return env_path


def _post_artifact(
    name: str,
    artifact_type: str,
    channel_id: str,
    description: str,
    extra_tags: list[list[str]],
    content: str,
) -> bool:
    """Post a genesis message for a project/workflow/template into a channel."""
    payload = json.dumps({
        "channel": channel_id,
        "content": content,
        "tags": [
            ["qortroller", "1"],
            ["artifact", artifact_type],
            ["artifact_name", name],
        ] + extra_tags,
    })
    rc, stdout, stderr = _qortroller_buzz(["publish"], stdin=payload, timeout=30)
    if rc != 0:
        print(f"[!] {artifact_type} genesis post failed: {stderr}", file=sys.stderr)
        return False
    try:
        data = json.loads(stdout)
        return data.get("accepted", False)
    except Exception:
        return False


def create_channel(name: str, description: str, visibility: str) -> Optional[str]:
    """Create a channel with the parent's key. Returns channel_id or None."""
    args = ["channels", "create", "--name", name, "--type", "stream", "--visibility", visibility]
    if description:
        args += ["--description", description]

    rc, stdout, stderr = _buzz_cli(args)
    if rc != 0:
        print(f"[!] channel create failed: {stderr}", file=sys.stderr)
        return None
    try:
        data = json.loads(stdout)
        channel_id = data.get("channel_id")
        print(f"[*] channel created: {channel_id}")
        return channel_id
    except Exception:
        print(f"[!] could not parse channel response: {stdout}", file=sys.stderr)
        return None


def create_project(name: str, description: str, goal: str) -> Optional[dict]:
    """Create a project channel and post a genesis event."""
    channel_id = create_channel(name, description, "open")
    if not channel_id:
        return None
    content = f'Project "{name}" started. Goal: {goal or description or "expand QorTroller"}. Collaborators welcome.'
    if _post_artifact(name, "project", channel_id, description, [], content):
        print(f"[*] project genesis posted to {channel_id}")
    return {"channel_id": channel_id, "name": name, "type": "project"}


def create_workflow(name: str, description: str, steps: str) -> Optional[dict]:
    """Create a workflow channel and post the workflow spec."""
    channel_id = create_channel(name, description, "open")
    if not channel_id:
        return None
    step_lines = [s.strip() for s in (steps or "").split(",") if s.strip()] or ["1. define", "2. execute", "3. verify"]
    content = f'Workflow "{name}":\n' + "\n".join(f"{i+1}. {s}" for i, s in enumerate(step_lines))
    extra_tags = [["workflow_steps", ",".join(step_lines)]]
    if _post_artifact(name, "workflow", channel_id, description, extra_tags, content):
        print(f"[*] workflow genesis posted to {channel_id}")
    return {"channel_id": channel_id, "name": name, "type": "workflow", "steps": step_lines}


def create_template(name: str, description: str, source: str) -> Optional[dict]:
    """Create a template channel and post a reusable template definition."""
    channel_id = create_channel(name, description, "open")
    if not channel_id:
        return None
    content = f'Template "{name}":\n{description or "Reusable QorTroller template."}\nSource/seed: {source or "manual"}'
    extra_tags = [["template_source", source or "manual"]]
    if _post_artifact(name, "template", channel_id, description, extra_tags, content):
        print(f"[*] template genesis posted to {channel_id}")
    return {"channel_id": channel_id, "name": name, "type": "template", "source": source or "manual"}


def brainstorm(topic: str, channel_id: str) -> bool:
    """Post a brainstorming seed to a brainstorm channel."""
    if not channel_id:
        print("[!] no brainstorm channel configured", file=sys.stderr)
        return False
    content = f"Brainstorm: {topic}. What novel QorTroller implementations or integrations could this unlock?"
    return _post_artifact(topic, "brainstorm", channel_id, topic, [], content)


def create_agent(name: str, role: str, about: str, post_birth: bool = True) -> Optional[dict]:
    """Create a child agent: generate key, set profile, write .env, optionally announce."""
    parent_key = os.environ.get("BUZZ_PRIVATE_KEY", "")
    if not parent_key:
        print("[!] BUZZ_PRIVATE_KEY required (parent key)", file=sys.stderr)
        return None

    parent_npub = _my_npub(parent_key)
    if not parent_npub:
        return None

    nsec, npub = _generate_key()
    relay_url = os.environ.get("BUZZ_RELAY_URL", "wss://qortroller.communities.buzz.xyz")
    env_path = _write_child_env(name, nsec, npub, relay_url, role, parent_npub)
    print(f"[*] child agent key written to {env_path}")

    # Set child profile
    child_about = about or f"Child QorTroller agent ({role}) minted by {parent_npub}."
    extra_env = {
        "BUZZ_PRIVATE_KEY": nsec,
        "BUZZ_RELAY_URL": relay_url,
    }
    rc, _, stderr = _buzz_cli(["users", "set-profile", "--name", name, "--about", child_about], extra_env=extra_env, timeout=30)
    if rc != 0:
        print(f"[!] child profile set failed (child may need relay invite): {stderr}", file=sys.stderr)
        # Not fatal — the key and .env are still created.
    else:
        print(f"[*] child profile set for {npub}")

    # Optional birth announcement on audit channel using parent key
    audit_channel = os.environ.get("BUZZ_AUDIT_CHANNEL_ID", "")
    if post_birth and audit_channel:
        birth_content = f"Agent minted: {name} ({role}) by {parent_npub} → child {npub}"
        payload = json.dumps({
            "channel": audit_channel,
            "content": birth_content,
            "tags": [
                ["qortroller", "1"],
                ["agent_mint", "1"],
                ["agent_name", name],
                ["agent_role", role],
                ["parent", parent_npub],
                ["child", npub],
            ],
        })
        rc, stdout, stderr = _qortroller_buzz(["publish"], stdin=payload, timeout=30)
        if rc != 0:
            print(f"[!] birth announcement failed: {stderr}", file=sys.stderr)
        else:
            try:
                data = json.loads(stdout)
                if data.get("accepted"):
                    print(f"[*] birth announcement posted to {audit_channel}")
            except Exception:
                pass

    return {
        "nsec": nsec,
        "npub": npub,
        "name": name,
        "role": role,
        "parent_npub": parent_npub,
        "env_path": str(env_path),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Agentic agent/channel factory for QorTroller Buzz.")
    sub = parser.add_subparsers(dest="cmd", required=True)

    ch = sub.add_parser("create-channel", help="Create a new channel")
    ch.add_argument("--name", required=True)
    ch.add_argument("--description", default="")
    ch.add_argument("--visibility", default="open", choices=["open", "restricted"])

    ag = sub.add_parser("create-agent", help="Create a new child agent")
    ag.add_argument("--name", required=True)
    ag.add_argument("--role", default="concierge")
    ag.add_argument("--about", default="")
    ag.add_argument("--no-birth-post", action="store_true", help="Skip audit-channel birth post")

    pr = sub.add_parser("create-project", help="Create a project channel with a genesis post")
    pr.add_argument("--name", required=True)
    pr.add_argument("--description", default="")
    pr.add_argument("--goal", default="")

    wf = sub.add_parser("create-workflow", help="Create a workflow channel with a spec post")
    wf.add_argument("--name", required=True)
    wf.add_argument("--description", default="")
    wf.add_argument("--steps", default="")

    tp = sub.add_parser("create-template", help="Create a template channel with a definition post")
    tp.add_argument("--name", required=True)
    tp.add_argument("--description", default="")
    tp.add_argument("--source", default="")

    br = sub.add_parser("brainstorm", help="Post a brainstorming seed to a brainstorm channel")
    br.add_argument("--topic", required=True)
    br.add_argument("--channel", default="", help="Brainstorm channel UUID (or BUZZ_BRAINSTORM_CHANNEL_ID)")

    args = parser.parse_args()

    if not os.environ.get("BUZZ_PRIVATE_KEY"):
        print("[!] BUZZ_PRIVATE_KEY (parent key) is required", file=sys.stderr)
        return 1

    if args.cmd == "create-channel":
        channel_id = create_channel(args.name, args.description, args.visibility)
        return 0 if channel_id else 1

    if args.cmd == "create-project":
        result = create_project(args.name, args.description, args.goal)
        return 0 if result else 1

    if args.cmd == "create-workflow":
        result = create_workflow(args.name, args.description, args.steps)
        return 0 if result else 1

    if args.cmd == "create-template":
        result = create_template(args.name, args.description, args.source)
        return 0 if result else 1

    if args.cmd == "brainstorm":
        channel_id = args.channel or os.environ.get("BUZZ_BRAINSTORM_CHANNEL_ID", "")
        return 0 if brainstorm(args.topic, channel_id) else 1

    if args.cmd == "create-agent":
        result = create_agent(args.name, args.role, args.about, post_birth=not args.no_birth_post)
        if result:
            print(json.dumps({k: v for k, v in result.items() if k != "nsec"}, indent=2))
            print(f"[*] child nsec stored in: {result['env_path']}")
            return 0
        return 1

    return 1


if __name__ == "__main__":
    sys.exit(main())
