"""HWFL-1 Sensor A one-shot runner.

Invokes the `mythos_path_a_spec_impl_parity` variant (variant #16) and
renders findings as `audits/sensor-a-cycle-<N>-<YYYY-MM-DD>.md`. The
variant itself is pure-function; this runner is the operator-facing
emission surface (variants are introspectable via the Mythos cadence
engine; the runner produces a human-readable report).

Usage:
    python scripts/run_sensor_a.py                          # Cycle 1, today's date
    python scripts/run_sensor_a.py --cycle 2 --date 2026-06-15
    python scripts/run_sensor_a.py --stdout                 # print, do not write
"""
from __future__ import annotations

import argparse
import asyncio
import datetime as _dt
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from bridge.vapi_bridge.mythos_variants import mythos_path_a_spec_impl_parity  # noqa: E402


def _render_markdown(findings: list, cycle: int, date: str) -> str:
    lines: list[str] = []
    lines.append(f"# Sensor A — Cycle {cycle} Report ({date})\n")
    lines.append(
        "HWFL-1 Sensor A v0.1 — spec/impl parity probe against "
        "`docs/path-a-manufacturing-spec.md`. Generated by "
        "`scripts/run_sensor_a.py`; variant source "
        "`bridge/vapi_bridge/mythos_variants.py::mythos_path_a_spec_impl_parity`.\n"
    )
    lines.append(f"**Total emitted findings:** {len(findings)}\n")

    by_sev: dict[str, list] = {"CRITICAL": [], "HIGH": [], "MEDIUM": [], "LOW": []}
    for f in findings:
        by_sev.setdefault(f.severity, []).append(f)

    lines.append("\n## Summary by severity\n")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        lines.append(f"| {sev} | {len(by_sev.get(sev, []))} |")
    lines.append("")

    lines.append("\n## Findings\n")
    for i, f in enumerate(findings, 1):
        lines.append(f"### {i}. [{f.severity}] {f.variant}")
        lines.append(f"- **coherence_id:** `{f.coherence_id}`")
        if f.file_path:
            lines.append(f"- **file:** `{f.file_path}`")
        lines.append(f"- **description:** {f.description}")
        lines.append(f"- **recommended_fix:** {f.recommended_fix}")
        if f.evidence_sources:
            lines.append(f"- **evidence:** {', '.join(f'`{e}`' for e in f.evidence_sources)}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Run HWFL-1 Sensor A cycle")
    p.add_argument("--cycle", type=int, default=1)
    p.add_argument("--date", default=_dt.date.today().isoformat())
    p.add_argument("--stdout", action="store_true")
    args = p.parse_args(argv)

    findings = asyncio.run(mythos_path_a_spec_impl_parity(repo_root=_REPO_ROOT))
    md = _render_markdown(findings, args.cycle, args.date)

    if args.stdout:
        print(md)
        return 0

    out_dir = _REPO_ROOT / "audits"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / f"sensor-a-cycle-{args.cycle}-{args.date}.md"
    out_path.write_text(md, encoding="utf-8")
    print(f"Sensor A Cycle {args.cycle}: {len(findings)} findings -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
