#!/usr/bin/env python3
"""
VAPI Tournament Pre-Launch Preflight Validator (Phase 127)
==========================================================
Standalone script that evaluates all pre-launch conditions by calling
the bridge API and writes a structured report to docs/tournament-preflight-report.md.

Usage:
    python scripts/tournament_preflight.py [--base-url URL] [--api-key KEY] [--output PATH]

Conditions evaluated:
    P0 (BLOCKS activation):
      1. separation_ratio >= 1.0
      2. L4 calibration not stale (live_dim == calib_dim)
      3. gate_passed (consecutive_clean >= gate_n)
      4. cert_valid (enforcement certificate present and unexpired)
      5. audit_valid (activation audit chain intact)
    P1 (WARNS only):
      6. dual_primitive_gate_enabled
      7. epoch_window_enabled
      8. ioswarm_vhp_mint_enabled
"""
from __future__ import annotations

import argparse
import json
import sys
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path


def _get(base_url: str, path: str, api_key: str, method: str = "GET") -> dict:
    params = urllib.parse.urlencode({"api_key": api_key})
    url = f"{base_url}{path}?{params}"
    req = urllib.request.Request(url, method=method)
    with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310
        return json.loads(resp.read())


def run_preflight(base_url: str, api_key: str) -> dict:
    """POST to /agent/run-tournament-preflight and return result dict."""
    return _get(base_url, "/agent/run-tournament-preflight", api_key, method="POST")


def write_report(result: dict, output_path: Path) -> None:
    """Write a structured markdown report from preflight result."""
    ts = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    sep_ratio = result.get("conditions", {}).get("separation_ratio", "?")
    consecutive = result.get("conditions", {}).get("consecutive_clean", "?")

    def status(ok: bool) -> str:
        return "PASS" if ok else "FAIL"

    def warn(flag: bool) -> str:
        return "WARN (disabled)" if flag else "OK (enabled)"

    lines = [
        "# VAPI Tournament Pre-Launch Preflight Report",
        "",
        f"**Generated:** {ts}",
        f"**Overall:** {'READY' if result.get('overall_pass') else 'NOT READY'}",
        "",
        "## P0 Conditions (BLOCK activation if failed)",
        "",
        "| Condition | Value | Status |",
        "|-----------|-------|--------|",
        f"| separation_ratio ≥ 1.0 | {sep_ratio} | {status(result.get('separation_ok', False))} |",
        f"| L4 calibration fresh (live==calib dim) | — | {status(result.get('l4_ok', False))} |",
        f"| gate_passed (consecutive_clean ≥ gate_n) | {consecutive} | {status(result.get('gate_ok', False))} |",
        f"| cert_valid | — | {status(result.get('cert_ok', False))} |",
        f"| audit_valid | — | {status(result.get('audit_ok', False))} |",
        "",
        "## P1 Conditions (WARN only)",
        "",
        "| Condition | Status |",
        "|-----------|--------|",
        f"| dual_primitive_gate_enabled | {warn(result.get('dual_gate_warned', True))} |",
        f"| epoch_window_enabled | {warn(result.get('epoch_window_warned', True))} |",
        f"| ioswarm_vhp_mint_enabled | {warn(result.get('ioswarm_warned', True))} |",
        "",
        "## Raw Conditions",
        "",
        "```json",
        json.dumps(result.get("conditions", {}), indent=2),
        "```",
        "",
        "---",
        f"*Generated by `scripts/tournament_preflight.py` — VAPI Phase 127*",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[preflight] Report written to {output_path}")


def main() -> int:
    parser = argparse.ArgumentParser(description="VAPI Tournament Pre-Launch Preflight")
    parser.add_argument("--base-url", default="http://localhost:18080",
                        help="Bridge operator API base URL (default: http://localhost:18080)")
    parser.add_argument("--api-key", default="", help="Operator API key")
    parser.add_argument("--output", default="docs/tournament-preflight-report.md",
                        help="Output report path (default: docs/tournament-preflight-report.md)")
    args = parser.parse_args()

    base_url = args.base_url.rstrip("/")
    api_key  = args.api_key
    output   = Path(args.output)

    print(f"[preflight] Running tournament pre-launch preflight against {base_url}")
    try:
        result = run_preflight(base_url, api_key)
    except Exception as exc:
        print(f"[preflight] ERROR: {exc}", file=sys.stderr)
        return 1

    overall = result.get("overall_pass", False)
    print(f"[preflight] separation_ok={result.get('separation_ok')}")
    print(f"[preflight] l4_ok={result.get('l4_ok')}")
    print(f"[preflight] gate_ok={result.get('gate_ok')}")
    print(f"[preflight] cert_ok={result.get('cert_ok')}")
    print(f"[preflight] audit_ok={result.get('audit_ok')}")
    print(f"[preflight] overall_pass={overall}")

    write_report(result, output)
    return 0 if overall else 2


if __name__ == "__main__":
    sys.exit(main())
