// MSW browser worker setup for Storybook stories.
//
// Track classification: out-of-band-solo. NOT Phase 241. NOT in the sequential
// VAPI protocol chain.
//
// The worker is registered by Storybook's MSW addon at preview load time; the
// service-worker file lives at `public/mockServiceWorker.js` (generated by
// `npx msw init public/`).

import { setupWorker } from "msw/browser";
import { handlers } from "./handlers";

export const worker = setupWorker(...handlers);
